"use client";
import MediaEditor from "./media-editor";
import LoyaltyEditor from "./loyalty-editor";
import {useState,useEffect} from "react";
import {LayoutDashboard,Watch,Video,Tag,Settings,ArrowUpRight,Plus,Upload,Check} from "lucide-react";
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from "@/components/ui/sidebar";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from "@/components/ui/alert-dialog";
import {Switch} from "@/components/ui/switch";
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from "@/components/ui/table";
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
import {Product,defaults,money} from "@/lib/catalog";
import AdminLogin from "./admin-login";
const empty:Product={id:"",name:"",collection:"",price:50000,description:"",specs:"",images:[],featured:true,active:true,paymentPlan:"Bank transfer. Contact us to discuss payment arrangements."};
export default function Dashboard({authorized}:{authorized:boolean}){
const [tab,setTab]=useState("Overview"),[settings,setSettings]=useState(defaults),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<any[]>([]),[editing,setEditing]=useState<Product|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[confirm,setConfirm]=useState<any>(null),[connected,setConnected]=useState(false),[loyaltyOffers,setLoyaltyOffers]=useState<any[]>([]);
async function load(){try{const r=await fetch("/api/admin");const d:any=await r.json();if(!r.ok)throw Error(d.error);setSettings({...defaults,...d.settings});setProducts(d.products);setOrders(d.orders);setConnected(d.sheetsConfigured);setLoyaltyOffers(d.loyaltyOffers||[])}catch(e:any){setMessage(e.message)}}
useEffect(()=>{if(authorized)load()},[authorized]);
async function save(action:string,data?:any,id?:string){setBusy(true);setMessage("");try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,data,id})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(action==="sync"?(d.configured?"Google Sheet updated.":"Connect a Google service account and sheet first."):d.sync?.error||"Changes saved.");if(action==="product")setEditing(null);await load()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
async function upload(file:File|undefined,target:string){if(!file)return;setBusy(true);setMessage("Uploading "+file.name+"…");try{const f=new FormData();f.set("file",file);const r=await fetch("/api/upload",{method:"POST",body:f});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(target==="product")setEditing(p=>p?{...p,images:[...p.images,d.url]}:p);else setSettings(s=>({...s,[target]:d.url}));setMessage("Uploaded. Save your changes to publish this media.")}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
const paid=orders.filter(o=>o.status==="paid"),customers=new Set(orders.map(o=>o.phone)).size;
const chart=Array.from({length:7},(_,i)=>{const d=new Date();d.setUTCDate(d.getUTCDate()-6+i);const day=d.toISOString().slice(0,10);const rows=orders.filter(o=>new Date(o.created).toISOString().startsWith(day));return {day:d.toLocaleDateString("en",{weekday:"short",timeZone:"UTC"}),Requests:rows.length,Purchases:rows.filter(o=>o.status==="paid").length}});
const tabs=[["Overview",LayoutDashboard],["Products",Watch],["Home video",Video],["Page covers",Video],["The Details",Watch],["Customer offers",Tag],["First-purchase offer",Tag],["Store settings",Settings]] as const;
return <SidebarProvider><Sidebar style={{background:"#f5f6f7"}}><SidebarHeader style={{padding:28}}><a className="brand" href="/">Stacdial</a><small style={{textAlign:"center"}}>Store management</small></SidebarHeader><SidebarContent style={{padding:15}}><SidebarMenu>{tabs.map(([name,Icon])=><SidebarMenuItem key={name}><SidebarMenuButton isActive={tab===name} onClick={()=>setTab(name)} style={{padding:15,height:48,borderRadius:12}}><Icon size={19}/><span>{name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><a href="/" className="textlink" style={{margin:"35px 15px"}}>View storefront ↗</a></SidebarContent></Sidebar><SidebarInset style={{background:"#f5f6f7"}}><main className="adminmain"><SidebarTrigger/><div className="sectionhead" style={{marginTop:25,marginBottom:25}}><div><span className="eyebrow muted">Your workspace</span><h1 style={{marginTop:12}}>{tab}</h1></div>{tab==="Products"&&<button className="pill" disabled={!authorized} onClick={()=>setEditing({...empty,id:crypto.randomUUID()})}><Plus size={16}/>Add watch</button>}</div>
{!authorized&&<AdminLogin/>}
{message&&<p className="notice" role="status">{message}</p>}
{tab==="Overview"&&<><div className="metrics"><div className="panel metric"><span className="muted">Confirmed sales</span><strong>{money(paid.reduce((sum,o)=>sum+o.total/100,0))}</strong><small>Verified bank transfers</small></div><div className="panel metric"><span className="muted">Purchases</span><strong>{paid.length}</strong><small>{orders.length-paid.length} awaiting payment</small></div><div className="panel metric"><span className="muted">Customers</span><strong>{customers}</strong><small>Unique WhatsApp numbers</small></div></div><div className="panel"><div className="sectionhead" style={{marginBottom:20}}><h3>Store activity</h3><small>Last 7 days · UTC</small></div><div style={{height:260}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="Requests" stroke="#1889BE" fill="#DEE6EF"/><Area type="monotone" dataKey="Purchases" stroke="#042950" fill="#042950" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div></div><div className="panel"><h3>Purchase requests</h3>{orders.length?<Table><TableHeader><TableRow>{["Customer","Watch","Total","Status",""].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{orders.map(o=><TableRow key={o.id}><TableCell>{o.name}<br/><small>{o.phone} · {o.id}</small></TableCell><TableCell>{o.product_name}{o.note&&<p className="muted">{o.note}</p>}</TableCell><TableCell>{money(o.total/100)}{o.discount>0&&<small style={{display:"block"}}>Saved {money(o.discount/100)}</small>}</TableCell><TableCell>{o.status==="paid"?"Paid":"Awaiting payment"}</TableCell><TableCell>{o.status!=="paid"&&<button className="pill outline" onClick={()=>setConfirm(o)} disabled={busy}>Mark paid</button>}</TableCell></TableRow>)}</TableBody></Table>:<p className="muted">No purchase requests yet. New requests will appear here.</p>}</div></>}
{tab==="Products"&&<>{products.length?products.map(p=><div key={p.id} className="panel adminproduct"><img src={p.images[0]} alt={p.name}/><div><h3 style={{marginBottom:5}}>{p.name}</h3><small>{p.collection} · {money(p.price)} · {p.active?"Published":"Hidden"}</small></div><button className="pill outline" onClick={()=>setEditing(p)}>Edit watch</button></div>):<div className="panel"><h3>Your collection starts here.</h3><p className="muted">Add a watch with its real photographs, price, specifications and payment details. The storefront's reference collection disappears when you publish your first product.</p><button className="pill" disabled={!authorized} onClick={()=>setEditing({...empty,id:crypto.randomUUID()})}>Add your first watch</button></div>}</>}
{tab==="Home video"&&<div className="panel"><h3>The opening frame.</h3><p className="muted">Upload separate films for desktop and mobile. Muted looping playback, with a pause control for visitors. MP4 or WebM, up to 80 MB each.</p><div className="split">{[["desktopVideo","Desktop film · landscape"],["mobileVideo","Mobile film · portrait"],["poster","Fallback image"]].map(([key,label])=><div key={key}><h3 style={{fontSize:18}}>{label}</h3>{settings[key as keyof typeof settings]&&(key==="poster"?<img src={settings.poster} alt="Hero fallback" style={{height:170,width:"100%",objectFit:"cover",borderRadius:15}}/>:<video controls src={String(settings[key as keyof typeof settings])} style={{height:170,width:"100%",background:"#020306",borderRadius:15}}/>)}<label className="pill outline" style={{margin:"20px 0"}}><Upload size={16}/>Choose file<input type="file" hidden disabled={!authorized||busy} accept={key==="poster"?"image/jpeg,image/png,image/webp":"video/mp4,video/webm"} onChange={e=>upload(e.target.files?.[0],key)}/></label>{key!=="poster"&&<button disabled={!authorized} className="textlink" style={{marginLeft:20}} onClick={()=>setSettings({...settings,[key]:""})}>Remove</button>}</div>)}</div><button className="pill" disabled={!authorized||busy} onClick={()=>save("settings",settings)}>Save home media</button></div>}
{tab==="First-purchase offer"&&<div className="split"><div className="panel form"><h3>A considered welcome.</h3><label style={{display:"flex",justifyContent:"space-between"}}>Offer enabled<Switch checked={settings.offerEnabled} disabled={!authorized} onCheckedChange={v=>setSettings({...settings,offerEnabled:v})}/></label><label>Discount percentage<input type="number" min={0} max={50} value={settings.offerPercent} disabled={!authorized} onChange={e=>setSettings({...settings,offerPercent:Number(e.target.value)})}/></label><label>Heading<input value={settings.offerTitle} disabled={!authorized} onChange={e=>setSettings({...settings,offerTitle:e.target.value})}/></label><label>Message<textarea value={settings.offerText} disabled={!authorized} onChange={e=>setSettings({...settings,offerText:e.target.value})}/></label><button className="pill" disabled={!authorized||busy} onClick={()=>save("settings",settings)}>Save offer</button><small>Appears after 25 seconds, once the visitor reaches featured watches. Once per session. Claimed offers are stored securely for 30 days. The current percentage is calculated when the request is submitted; saved orders keep their original totals.</small></div><div className="panel offer"><span className="eyebrow">Offer preview</span><strong>{settings.offerPercent}%</strong><h3>{settings.offerTitle}</h3><p className="muted">{settings.offerText}</p><span className="pill">Claim my offer</span></div></div>}
{tab==="Page covers"&&<><div className="split">{(["shop","about"] as const).map(k=><MediaEditor key={k} title={k==="shop"?"Shop cover":"About cover"} src={settings[k+"Cover" as keyof typeof settings] as string} crop={settings[k+"Crop" as keyof typeof settings] as any} mobileCrop={settings[k+"MobileCrop" as keyof typeof settings] as any} disabled={!authorized||busy} onImage={f=>upload(f,k+"Cover")} onCrop={v=>setSettings({...settings,[k+"Crop"]:v})} onMobileCrop={v=>setSettings({...settings,[k+"MobileCrop"]:v})}/>)}</div><div style={{display:"flex",gap:20,marginBottom:20}}><button className="textlink" disabled={!authorized} onClick={()=>setSettings({...settings,shopCover:""})}>Remove Shop cover</button><button className="textlink" disabled={!authorized} onClick={()=>setSettings({...settings,aboutCover:""})}>Remove About cover</button></div><button className="pill" disabled={!authorized||busy} onClick={()=>save("settings",settings)}>Save page covers</button></>}
{tab==="The Details"&&<div className="split"><MediaEditor title="Editorial feature photograph" src={settings.editorialImage} crop={settings.editorialCrop} mobileCrop={settings.editorialMobileCrop} disabled={!authorized||busy} onImage={f=>upload(f,"editorialImage")} onCrop={v=>setSettings({...settings,editorialCrop:v})} onMobileCrop={v=>setSettings({...settings,editorialMobileCrop:v})}/><div className="panel form"><label>Headline<input value={settings.editorialTitle} disabled={!authorized} onChange={e=>setSettings({...settings,editorialTitle:e.target.value})}/></label><label>Copy<textarea value={settings.editorialText} disabled={!authorized} onChange={e=>setSettings({...settings,editorialText:e.target.value})}/></label><label style={{display:"flex",gap:20}}>Show consultation section<Switch disabled={!authorized} checked={settings.consultationEnabled} onCheckedChange={v=>setSettings({...settings,consultationEnabled:v})}/></label><small>Customers request a suitable consultation time on WhatsApp. No appointment is confirmed automatically.</small><button className="pill" disabled={!authorized||busy} onClick={()=>save("settings",settings)}>Save editorial feature</button></div></div>}
{tab==="Customer offers"&&<LoyaltyEditor orders={orders} offers={loyaltyOffers} disabled={!authorized||busy} save={save}/>}
{tab==="Store settings"&&<div className="panel form"><label>Business WhatsApp number<input disabled={!authorized} placeholder="947XXXXXXXX" value={settings.whatsapp} onChange={e=>setSettings({...settings,whatsapp:e.target.value.replace(/\D/g,"")})}/><small>International format, digits only. Customers choose to send the pre-filled purchase message.</small></label><label>About Stacdial<textarea disabled={!authorized} value={settings.about} onChange={e=>setSettings({...settings,about:e.target.value})}/></label><label>Google Sheet ID<input disabled={!authorized} value={settings.sheetsId} onChange={e=>setSettings({...settings,sheetsId:e.target.value})}/><small>Create a dedicated tab named Orders. Share the sheet with your configured Google service account. The Orders tab is managed by this store.</small></label><p className="notice">{connected?"Google service account configured.":"Google service account is not connected yet. Its private credential must be installed securely before syncing."}</p><div style={{display:"flex",gap:15,flexWrap:"wrap"}}><button disabled={!authorized||busy} className="pill" onClick={()=>save("settings",settings)}>Save store settings</button><button disabled={!authorized||busy||!connected} className="pill outline" onClick={()=>save("sync")}>Sync Google Sheet</button></div><small>Orders are retained if Google is unavailable. Use Sync Google Sheet to retry. Sales and payment totals are always stored in the dashboard first.</small></div>}
</main></SidebarInset>
<Dialog open={!!editing} onOpenChange={v=>{if(!v)setEditing(null)}}><DialogContent style={{maxWidth:750,width:"calc(100% - 32px)"}}><DialogTitle>{editing?.name||"Add a watch"}</DialogTitle><DialogDescription>Use actual product photos and verified specifications.</DialogDescription>{editing&&<form className="form" onSubmit={e=>{e.preventDefault();save("product",editing)}}><div className="split"><label>Watch name<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Collection<input required value={editing.collection} onChange={e=>setEditing({...editing,collection:e.target.value})}/></label></div><label>Price · LKR<input type="number" min={1} step=".01" required value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>Brief description<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Specifications<textarea value={editing.specs} onChange={e=>setEditing({...editing,specs:e.target.value})}/></label><label>Payment plans and terms<textarea value={editing.paymentPlan} onChange={e=>setEditing({...editing,paymentPlan:e.target.value})}/></label><div><label className="pill outline"><Upload size={16}/>Add product photo<input type="file" hidden accept="image/jpeg,image/png,image/webp" disabled={busy||editing.images.length>=12} onChange={e=>upload(e.target.files?.[0],"product")}/></label><div className="thumbs">{editing.images.map((src,i)=><button type="button" key={src+i} title="Remove photo" aria-label={"Remove photo "+(i+1)} onClick={()=>setEditing({...editing,images:editing.images.filter((_,j)=>i!==j)})}><img src={src} alt={"Product photo "+(i+1)}/></button>)}</div><small>First photo is the cover. Up to 12 images. Click an image to remove it.</small></div><label style={{display:"flex",gap:15}}>Featured on Home<Switch checked={editing.featured} onCheckedChange={v=>setEditing({...editing,featured:v})}/></label><label style={{display:"flex",gap:15}}>Published<Switch checked={editing.active} onCheckedChange={v=>setEditing({...editing,active:v})}/></label><button className="pill" disabled={busy||!editing.images.length}>{busy?"Saving…":"Save watch"}</button></form>}</DialogContent></Dialog>
<AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent style={{background:"white"}}><AlertDialogTitle>Confirm payment received</AlertDialogTitle><AlertDialogDescription>Mark {confirm?.id} as paid only after verifying the bank transfer of {money((confirm?.total||0)/100)}. This updates sales totals and the connected sheet.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{save("paid",undefined,confirm.id);setConfirm(null)}}>Confirm paid</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</SidebarProvider>}
