"use client";
import {useState} from "react";
import {Slider} from "@/components/ui/slider";
import {FramedImage} from "../framed-image";
import {Crop,defaultCrop} from "@/lib/catalog";
export default function MediaEditor({title,src,crop,mobileCrop,onImage,onCrop,onMobileCrop,disabled=false}:{title:string;src:string;crop:Crop;mobileCrop:Crop;onImage:(f:File|undefined)=>void;onCrop:(c:Crop)=>void;onMobileCrop:(c:Crop)=>void;disabled?:boolean}){
const [mobile,setMobile]=useState(false),value=(mobile?mobileCrop:crop)||defaultCrop;
const update=(v:Partial<Crop>)=>(mobile?onMobileCrop:onCrop)({...value,...v});
return <div className="panel"><h3>{title}</h3><label className="pill outline">Choose cover image<input type="file" hidden disabled={disabled} accept="image/jpeg,image/png,image/webp" onChange={e=>onImage(e.target.files?.[0])}/></label>{src?<><div className="crop-device"><button type="button" aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button type="button" aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile</button></div><div className="crop-preview" style={{width:mobile?195:"100%",height:"auto",aspectRatio:mobile?"390 / 300":"1440 / 390"}}><FramedImage src={src} alt={title+" crop preview"} crop={value} mobileCrop={value}/></div><div className="crop-controls"><label>Frame mode<select value={value.fit} disabled={disabled} onChange={e=>update({fit:e.target.value as Crop["fit"]})}><option value="cover">Fill frame / crop</option><option value="contain">Fit whole image</option></select></label><label>Horizontal position · {value.x}%<Slider aria-label={title+" horizontal crop"} value={[value.x]} min={0} max={100} step={1} disabled={disabled} onValueChange={v=>update({x:v[0]})}/></label><label>Vertical position · {value.y}%<Slider aria-label={title+" vertical crop"} value={[value.y]} min={0} max={100} step={1} disabled={disabled} onValueChange={v=>update({y:v[0]})}/></label><label>Zoom · {value.zoom.toFixed(2)}×<Slider aria-label={title+" crop zoom"} value={[value.zoom]} min={1} max={3} step={.05} disabled={disabled} onValueChange={v=>update({zoom:v[0]})}/></label><button className="textlink" type="button" disabled={disabled} onClick={()=>update(defaultCrop)}>Reset this crop</button></div><p className="muted" style={{fontSize:13,marginTop:18}}>The original stays intact. Position and zoom are saved separately for desktop and mobile.</p></>:<p className="muted" style={{marginTop:20}}>No cover image selected.</p>}</div>
}
