"use client";
import {useState} from "react";
import {Search,ArrowUpRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Product,money} from "@/lib/catalog";
export default function SiteHeader({products,active=""}:{products:Product[];active?:string}){
const [open,setOpen]=useState(false),[term,setTerm]=useState(""),[mega,setMega]=useState(false);
const needle=term.trim().toLowerCase(),results=products.filter(p=>(p.name+" "+p.collection+" "+p.description).toLowerCase().includes(needle));
const collections=[...new Set(["Everyday","Dress","Sport",...products.map(p=>p.collection)])].filter(c=>c.toLowerCase().includes(needle));
return <><header className="topbar v2-header" onMouseLeave={()=>setMega(false)} onKeyDown={e=>{if(e.key==="Escape")setMega(false)}}><nav className="navleft" aria-label="Main navigation"><a aria-current={active==="home"?"page":undefined} href="/">Home</a><div className="shop-nav" onMouseEnter={()=>setMega(true)}><a href="/shop" aria-current={active==="shop"?"page":undefined}>Shop</a><button className="collection-toggle" aria-label="Show collections" aria-expanded={mega} onClick={()=>setMega(!mega)}>⌄</button></div><a href="/about" aria-current={active==="about"?"page":undefined}>About</a><a href="/login" aria-current={active==="login"?"page":undefined}>Login</a></nav><a className="brand" href="/">Stacdial</a><form className="search desktop-search" action="/shop"><Search size={17}/><input name="q" aria-label="Search watches" placeholder="Search watches"/></form><button className="search search-trigger mobile-search" onClick={()=>{setMega(false);setOpen(true)}} aria-label="Search watches"><Search size={18}/></button>{mega&&<div className="mega"><p className="eyebrow" style={{textAlign:"center"}}>Explore the collection</p><div className="megalist">{["Everyday","Dress","Sport"].map(c=>{const p=products.find(p=>p.collection.toLowerCase()===c.toLowerCase());return <a key={c} href={"/shop?collection="+encodeURIComponent(c)}>{p&&<img src={p.images[0]} alt=""/>}{c}</a>})}</div><div className="megafooter"><a href="/shop" className="textlink">View all watches</a></div></div>}</header><Dialog open={open} onOpenChange={setOpen}><DialogContent className="search-dialog" style={{maxWidth:720,width:"calc(100% - 32px)",padding:32}}><DialogTitle style={{fontSize:30,letterSpacing:"-.04em"}}>Find your watch.</DialogTitle><DialogDescription>Search a watch name, detail or collection.</DialogDescription><form action="/shop" className="search-field"><Search size={22}/><input autoFocus name="q" aria-label="Search watches and collections" placeholder="Start typing…" value={term} onChange={e=>setTerm(e.target.value)}/></form><div aria-live="polite" className="search-count">{needle?results.length+" watches found":"Explore the collections"}</div><div className="search-keywords">{collections.map(c=><a className="filter-chip" key={c} href={"/shop?collection="+encodeURIComponent(c)}>{c}<ArrowUpRight size={14}/></a>)}</div><div className="search-results">{(needle?results:products).slice(0,6).map(p=><a className="search-result" key={p.id} href={"/product/"+p.id}><img src={p.images[0]} alt=""/><span><strong>{p.name}</strong><small>{p.collection} · {money(p.price)}</small></span><ArrowUpRight size={18}/></a>)}</div>{needle&&!results.length&&!collections.length&&<p className="muted">No matches yet. Try a different name or collection.</p>}{needle&&<a className="textlink" href={"/shop?q="+encodeURIComponent(term)}>View all results</a>}</DialogContent></Dialog></>
}
