"use client";
import {useState,useEffect,useRef} from "react";
import {ArrowUpRight,Plus,Pause,Play,ArrowRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import SiteHeader from "./site-header";
import {FramedImage} from "./framed-image";
import {samples,defaults,money,Product} from "@/lib/catalog";
export default function Storefront({view,id}:{view:string;id?:string}){
const [products,setProducts]=useState<Product[]>(samples),[settings,setSettings]=useState(defaults),[quick,setQuick]=useState<Product|null>(null),[offer,setOffer]=useState(false),[claimed,setClaimed]=useState(false),[query,setQuery]=useState(""),[collection,setCollection]=useState(""),[sort,setSort]=useState("featured"),[photo,setPhoto]=useState(0),[paused,setPaused]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[order,setOrder]=useState<any>(null);
const video=useRef<HTMLVideoElement>(null),featured=useRef<HTMLElement>(null);
useEffect(()=>{fetch("/api/store").then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>{setProducts(d.hasCatalogue?d.products:samples);setSettings({...defaults,...d.settings});setClaimed(d.claimed)}).catch(()=>setError("The catalogue is temporarily unavailable. Please try again shortly."));setQuery(new URLSearchParams(location.search).get("q")||"");setCollection(new URLSearchParams(location.search).get("collection")||"")},[]);
useEffect(()=>{if(view!=="home"||!settings.offerEnabled||sessionStorage.getItem("stacdial-offer-seen")||claimed)return;let ready=false,seen=false;const show=()=>{if(ready&&seen&&!document.querySelector('[data-state="open"][role="dialog"]')){setOffer(true);sessionStorage.setItem("stacdial-offer-seen","1")}};const timer=setTimeout(()=>{ready=true;show()},25000);const observer=new IntersectionObserver(([e])=>{seen=e.isIntersecting;show()},{threshold:.2});if(featured.current)observer.observe(featured.current);return()=>{clearTimeout(timer);observer.disconnect()}},[view,settings.offerEnabled,claimed]);
useEffect(()=>{if(!video.current)return;const media=matchMedia("(prefers-reduced-motion: reduce)");if(media.matches){video.current.pause();setPaused(true)}},[settings.desktopVideo,settings.mobileVideo]);
const product=products.find(p=>p.id===id),filtered=products.filter(p=>(p.name+" "+p.collection).toLowerCase().includes(query.toLowerCase())&&(!collection||p.collection.toLowerCase()===collection.toLowerCase())).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:0);
async function claim(){setBusy(true);try{const r=await fetch("/api/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d:any=await r.json();if(!r.ok)throw Error(d.error);setClaimed(true);setOffer(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
async function requestPurchase(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);if(!sessionStorage.getItem("stacdial-request"))sessionStorage.setItem("stacdial-request",crypto.randomUUID());try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:product?.id,name:f.get("name"),phone:f.get("phone"),note:f.get("note"),offerCode:f.get("offerCode"),requestKey:sessionStorage.getItem("stacdial-request")||crypto.randomUUID()})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setOrder(d);sessionStorage.removeItem("stacdial-request")}catch(e:any){setError(e.message)}finally{setBusy(false)}}
function card(p:Product){return <article className="productcard" key={p.id}><button className="card-preview" onClick={()=>setQuick(p)} aria-label={"Quick view "+p.name}><div className="folder"><img className="back" src={p.images[1]||p.images[0]} alt=""/><img src={p.images[0]} alt={p.name}/><span className="badge" style={{visibility:"hidden"}} aria-hidden="true">{p.collection}</span><span className="plus"><Plus size={17}/></span></div></button><a className="collection-card-link" href={"/shop?collection="+encodeURIComponent(p.collection)} aria-label={"Browse "+p.collection+" watches"}>{p.collection}</a><button className="card-name" onClick={()=>setQuick(p)}><h3>{p.name}</h3></button><span className="muted">{p.demo?"Collection preview":"Superclone timepiece"}</span><div className="price">{p.demo?"Illustrative price · ":""}{money(p.price)}</div></article>}
return <><a className="skip" href="#content">Skip to content</a><SiteHeader products={products} active={view}/><main id="content">{view==="home"&&<><section className="hero">{settings.desktopVideo||settings.mobileVideo?<video ref={video} key={settings.desktopVideo+settings.mobileVideo} autoPlay muted loop playsInline poster={settings.poster} aria-label="Stacdial watch film"><source src={settings.mobileVideo||settings.desktopVideo} media="(max-width: 767px)"/><source src={settings.desktopVideo||settings.mobileVideo}/></video>:<img src={settings.poster} alt="Close-up of a watch dial"/>}<div className="herocopy"><span className="eyebrow">Superclone</span><h1>Premium Timepieces</h1><a className="pill light" href="/shop">Discover the collection <ArrowUpRight size={17}/></a></div>{(settings.desktopVideo||settings.mobileVideo)&&<button className="pause" aria-label={paused?"Play background video":"Pause background video"} onClick={()=>{if(video.current){paused?video.current.play():video.current.pause();setPaused(!paused)}}}>{paused?<Play size={16}/>:<Pause size={16}/>}</button>}</section><section className="section" ref={featured}><div className="sectionhead"><div><span className="eyebrow muted">The Stacdial selection</span><h2>A closer look.</h2></div><a className="textlink" href="/shop">View all watches ↗</a></div><div className="cards">{products.filter(p=>p.featured).map(card)}</div></section><section className="editorial-feature"><FramedImage src={settings.editorialImage} alt="The fine details of a watch dial" crop={settings.editorialCrop} mobileCrop={settings.editorialMobileCrop}/><div className="editorial-copy"><span className="eyebrow">The Details</span><h2>{settings.editorialTitle}</h2><p>{settings.editorialText}</p></div></section>{settings.consultationEnabled&&<section className="consultation-section"><div><span className="eyebrow muted">A personal perspective</span><h2>Find your fit.</h2><p className="muted">Every wrist is different. Let’s talk about the style, size and details that suit you.</p></div><a className="pill" href={"https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hello Stacdial, I would like to arrange a watch consultation. Could you help me choose a watch and confirm a suitable time?")} target="_blank" rel="noreferrer">Book a consultation <ArrowUpRight size={18}/></a></section>}</>}
{view==="shop"&&<><div className={"shopheading page-cover "+(settings.shopCover?"has-cover":"")}>{settings.shopCover&&<FramedImage src={settings.shopCover} alt="Stacdial collection" crop={settings.shopCrop} mobileCrop={settings.shopMobileCrop}/>}<div className="cover-copy"><span className="eyebrow">Home / Shop</span><h1>{collection?collection+".":"The collection."}</h1><p className="muted">Find the one that feels like you.</p></div></div><section className="section"><div className="toolbar"><div className="filter-line"><span>{filtered.length} timepieces {query&&"· "+query}</span>{collection&&<a className="filter-chip" href="/shop" aria-label="Clear collection filter">{collection} ×</a>}</div><select aria-label="Sort watches" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{filtered.length?<div className="cards">{filtered.map(card)}</div>:<p>No watches match your search. <a href="/shop" className="textlink">View the collection</a></p>}</section></>}
{view==="about"&&<>{settings.aboutCover&&<section className="page-cover has-cover about-cover"><FramedImage src={settings.aboutCover} alt="About Stacdial" crop={settings.aboutCrop} mobileCrop={settings.aboutMobileCrop}/><div className="cover-copy"><span className="eyebrow">About Stacdial</span><h1>A feeling. Within reach.</h1></div></section>}<article className="reading">{!settings.aboutCover&&<><span className="eyebrow">About Stacdial</span><h1 style={{margin:"24px 0 35px"}}>A feeling.<br/>Within reach.</h1></>}<p>{settings.about}</p><p>Browse the collection, take a closer look, and speak with us before making a decision. Purchase requests are handled personally over WhatsApp, with payment by bank transfer.</p><div className="notice">Our watches are replicas, not authentic products of the original manufacturers. Stacdial is independent and is not affiliated with those brands.</div><a className="pill" href="/shop">Explore the collection <ArrowRight size={18}/></a></article></>}
{view==="product"&&(product?<section className="productdetail"><div><img className="gallerymain" src={product.images[photo]||product.images[0]} alt={product.name+" — image "+(photo+1)}/><div className="thumbs">{product.images.map((src,i)=><button aria-label={"View photo "+(i+1)} aria-pressed={photo===i} onClick={()=>setPhoto(i)} key={src+i}><img src={src} alt=""/></button>)}</div></div><div><a href="/shop" className="eyebrow muted">Shop / {product.collection}</a><h1>{product.name}</h1><p className="muted">{product.description}</p><div className="pricebig">{money(product.price)}</div>{claimed&&settings.offerEnabled&&<p className="success" style={{marginTop:12}}>First-purchase offer claimed · {settings.offerPercent}% off eligible purchases</p>}<div className="purchase"><h3>The details</h3><p>{product.specs}</p><h3>Payment</h3><p>{product.paymentPlan}</p><p className="muted" style={{fontSize:14}}>Request your watch below. We confirm availability and share bank details on WhatsApp. Your order is marked paid after we verify the transfer.</p>{product.demo?<div className="notice">Collection preview only. This is reference imagery, not a product offered for sale. Purchases open once the actual catalogue is added.</div>:order?<div className="notice"><h3>Request received.</h3><p>Reference: {order.id}<br/>Total: {money(order.total)}</p><a className="pill" href={order.whatsappUrl} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a><p style={{marginTop:15}}>Press Send in WhatsApp to share your request.</p></div>:<form className="form" onSubmit={requestPurchase}><label>Your name<input required name="name" maxLength={100} autoComplete="name"/></label><label>WhatsApp number<input required name="phone" type="tel" autoComplete="tel" maxLength={25}/></label><label>Returning-customer offer code <span className="muted">Optional</span><input name="offerCode" maxLength={40} placeholder="Your personal code" autoComplete="off"/></label><label>Anything you would like to ask? <span className="muted">Optional</span><textarea name="note" maxLength={1000}/></label><button className="pill" disabled={busy||!settings.whatsapp}>{busy?"Saving your request…":"Request to purchase"}</button>{!settings.whatsapp&&<small>Purchase requests are not open yet.</small>}</form>}</div></div></section>:<div className="reading"><h2>Watch not found</h2><a href="/shop">Return to the collection</a></div>)}
{error&&<p className="notice error" role="alert" style={{margin:"20px 7%"}}>{error}</p>}</main>
<footer className="footer"><div><div className="brand">Stacdial</div><span className="muted">Independent replica watch retailer · Sri Lanka</span></div><nav><a href="/">Home</a><a href="/shop">Shop</a><a href="/about">About</a><a href="/login">Login</a></nav></footer>
<Dialog open={!!quick} onOpenChange={v=>{if(!v)setQuick(null)}}><DialogContent style={{maxWidth:850,width:"calc(100% - 32px)",padding:35}}>{quick&&<div className="quickgrid"><img src={quick.images[0]} alt={quick.name}/><div><span className="eyebrow muted">{quick.collection}</span><DialogTitle style={{fontSize:34,letterSpacing:"-.04em",margin:"15px 0"}}>{quick.name}</DialogTitle><DialogDescription style={{lineHeight:1.7,marginBottom:20}}>{quick.description}</DialogDescription><p className="pricebig">{money(quick.price)}</p><a className="pill" href={"/product/"+quick.id}>Explore this watch <ArrowUpRight size={18}/></a></div></div>}</DialogContent></Dialog>
<Dialog open={offer} onOpenChange={setOffer}><DialogContent><div className="offer"><span className="eyebrow">A first welcome</span><strong>{settings.offerPercent}%</strong><DialogTitle style={{fontSize:30,margin:"5px 0 15px"}}>{settings.offerTitle}</DialogTitle><DialogDescription>{settings.offerText} Applied to your first eligible purchase request.</DialogDescription><button className="pill" style={{margin:"25px 0 15px",width:"100%"}} disabled={busy} onClick={claim}>{busy?"Claiming…":"Claim my offer"}</button><button className="textlink" onClick={()=>setOffer(false)}>Continue browsing</button><p className="muted" style={{fontSize:12,marginTop:20}}>One first-purchase offer per customer. No payment required to claim.</p></div></DialogContent></Dialog>
</>}
