"use client";
import {useState,useEffect} from "react";
import {ArrowUpRight,Plus,ArrowRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import SiteHeader from "./site-header";
import SiteFooter from "./site-footer";
import {FramedImage} from "./framed-image";
import {samples,defaults,money,Product,orderedFeaturedProducts,type StoreSettings} from "@/lib/catalog";
import Link from "next/link";
type StorefrontProps={view:string;id?:string;initialProducts?:Product[];initialSettings?:StoreSettings;initialClaimed?:boolean;initialUnavailable?:boolean;initialQuery?:string;initialCollection?:string};
type PurchaseResponse={id:string;total:number;whatsappUrl:string;error?:string};
export default function Storefront({view,id,initialProducts=samples,initialSettings=defaults,initialClaimed=false,initialUnavailable=false,initialQuery="",initialCollection=""}:StorefrontProps){
const [products]=useState<Product[]>(initialProducts),[settings]=useState(initialSettings),[quick,setQuick]=useState<Product|null>(null),[offer,setOffer]=useState(false),[claimed,setClaimed]=useState(initialClaimed),[sort,setSort]=useState("featured"),[photo,setPhoto]=useState(0),[error,setError]=useState(initialUnavailable?"Live catalogue data is temporarily unavailable. Reference items are shown below.":""),[busy,setBusy]=useState(false),[order,setOrder]=useState<PurchaseResponse|null>(null),query=initialQuery,collection=initialCollection;
useEffect(()=>{if(view!=="home"||!settings.offerEnabled||claimed||sessionStorage.getItem("stacdial-offer-dismissed"))return;const timer=setTimeout(()=>setOffer(true),7000);return()=>clearTimeout(timer)},[view,settings.offerEnabled,claimed]);
const product=products.find(p=>p.id===id),featuredProducts=orderedFeaturedProducts(products,settings.featuredProductIds),filtered=products.filter(p=>(p.name+" "+p.collection).toLowerCase().includes(query.toLowerCase())&&(!collection||p.collection.toLowerCase()===collection.toLowerCase())).sort((a,b)=>sort==="low"?a.price-b.price:sort==="high"?b.price-a.price:0);
async function claim(){setBusy(true);try{const r=await fetch("/api/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||"Unable to claim offer");sessionStorage.setItem("stacdial-offer-dismissed","1");setClaimed(true);setOffer(false)}catch(error:unknown){setError(error instanceof Error?error.message:"Unable to claim offer")}finally{setBusy(false)}}
function dismissOffer(){sessionStorage.setItem("stacdial-offer-dismissed","1");setOffer(false)}
async function requestPurchase(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);if(!sessionStorage.getItem("stacdial-request"))sessionStorage.setItem("stacdial-request",crypto.randomUUID());try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:product?.id,name:f.get("name"),phone:f.get("phone"),note:f.get("note"),offerCode:f.get("offerCode"),requestKey:sessionStorage.getItem("stacdial-request")||crypto.randomUUID()})});const d=await r.json() as PurchaseResponse;if(!r.ok)throw Error(d.error||"Unable to save your request");setOrder(d);sessionStorage.removeItem("stacdial-request")}catch(error:unknown){setError(error instanceof Error?error.message:"Unable to save your request")}finally{setBusy(false)}}
function card(p:Product){const content=<><div className="watch-card-media">{p.images[0]?<img src={p.images[0]} alt={p.name} loading="lazy" decoding="async"/>:<div className="watch-card-placeholder" aria-hidden="true"><span>STACDIAL</span></div>}<span className="watch-card-action" aria-hidden="true"><Plus size={17}/></span></div><div className="watch-card-copy"><h3>{p.name}</h3><p>{p.modelReference||p.specs}</p><strong>{p.demo?"Details coming soon":money(p.price)}</strong></div></>;return <article className={"productcard watch-product-card"+(p.demo?" is-preview":"")} key={p.id}><Link href={"/shop/"+(p.slug||p.id)} aria-label={"View "+p.name}>{content}</Link></article>}
return <><a className="skip" href="#content">Skip to content</a><SiteHeader products={products} active={view}/><main id="content">{view==="home"&&<>{settings.heroEnabled&&<section className="hero">{settings.desktopVideo||settings.mobileVideo?<video key={settings.desktopVideo+settings.mobileVideo} autoPlay muted loop playsInline poster={settings.poster} aria-label="Stacdial watch film"><source src={settings.mobileVideo||settings.desktopVideo} media="(max-width: 767px)"/><source src={settings.desktopVideo||settings.mobileVideo}/></video>:<img src={settings.poster} alt="Close-up of a watch dial"/>}<div className="herocopy"><span className="eyebrow">{settings.heroEyebrow}</span><h1>{settings.heroHeadline}</h1>{settings.heroText&&<p>{settings.heroText}</p>}<Link className="pill light" href={settings.heroButtonLink}>{settings.heroButtonLabel} <ArrowUpRight size={17}/></Link></div></section>}{settings.featuredEnabled&&<section className="section featured-products-section"><div className="sectionhead"><div><span className="eyebrow muted">{settings.featuredEyebrow}</span><h2>{settings.featuredTitle==="A closer look."?"Featured products.":settings.featuredTitle}</h2>{settings.featuredText&&<p className="muted">{settings.featuredText}</p>}</div><Link className="textlink" href={settings.featuredButtonLink}>{settings.featuredButtonLabel} ↗</Link></div>{featuredProducts.length?<div className="cards watch-product-grid">{featuredProducts.slice(0,6).map(card)}</div>:<div className="notice">Featured watches will appear here once selected.</div>}</section>}<section className="editorial-feature"><FramedImage src={settings.editorialImage==="/images/hero.jpg"?defaults.editorialImage:settings.editorialImage} mobileSrc={settings.editorialImage===defaults.editorialImage||settings.editorialImage==="/images/hero.jpg"?"/images/editorial-details-mobile.jpg":undefined} alt="A tailored look styled with a refined wristwatch" crop={settings.editorialCrop} mobileCrop={settings.editorialMobileCrop}/><div className="editorial-copy"><span className="eyebrow">The Details</span><h2>{settings.editorialTitle}</h2><p>{settings.editorialText}</p></div></section>{settings.consultationEnabled&&<section className="consultation-section"><div><span className="eyebrow muted">A personal perspective</span><h2>Find your fit.</h2><p className="muted">Every wrist is different. Let’s talk about the style, size and details that suit you.</p></div><a className="pill" href={"https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hello Stacdial, I would like to arrange a watch consultation. Could you help me choose a watch and confirm a suitable time?")} target="_blank" rel="noreferrer">Book a consultation <ArrowUpRight size={18}/></a></section>}</>}
{view==="shop"&&<><div className="shopheading page-cover has-cover"><FramedImage src={settings.shopCover||defaults.shopCover} mobileSrc={!settings.shopCover||settings.shopCover===defaults.shopCover?"/images/shop-collection-cover-mobile.jpg":undefined} alt="A curated collection of watches above a planetary horizon" crop={settings.shopCrop} mobileCrop={settings.shopMobileCrop}/><div className="cover-copy"><span className="eyebrow">Home / Shop</span><h1>{collection?collection+" watches.":"The collection."}</h1><p className="muted">Individual watches, curated by Stacdial.</p></div></div><section className="section"><div className="toolbar"><div className="filter-line"><span>{filtered.length} timepieces {query&&"· "+query}</span>{collection&&<Link className="filter-chip" href="/shop" aria-label="Clear collection filter">{collection} ×</Link>}</div><select aria-label="Sort watches" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{filtered.length?<div className="cards watch-product-grid">{filtered.map(card)}</div>:<p>No watches match this collection or search. <Link href="/shop" className="textlink">View all watches</Link></p>}</section></>}
{view==="about"&&<>{settings.aboutCover&&<section className="page-cover has-cover about-cover"><FramedImage src={settings.aboutCover} alt="About Stacdial" crop={settings.aboutCrop} mobileCrop={settings.aboutMobileCrop}/><div className="cover-copy"><span className="eyebrow">About Stacdial</span><h1>A feeling. Within reach.</h1></div></section>}<article className="reading">{!settings.aboutCover&&<><span className="eyebrow">About Stacdial</span><h1 style={{margin:"24px 0 35px"}}>A feeling.<br/>Within reach.</h1></>}<p>{settings.about}</p><p>Browse the collection, take a closer look, and speak with us before making a decision. Purchase requests are handled personally over WhatsApp, with payment by bank transfer.</p><div className="notice">Our watches are replicas, not authentic products of the original manufacturers. Stacdial is independent and is not affiliated with those brands.</div><Link className="pill" href="/shop">Explore the collection <ArrowRight size={18}/></Link></article></>}
{view==="product"&&(product?<section className="productdetail"><div><img className="gallerymain" src={product.images[photo]||product.images[0]} alt={product.name+" — image "+(photo+1)}/><div className="thumbs">{product.images.map((src,i)=><button aria-label={"View photo "+(i+1)} aria-pressed={photo===i} onClick={()=>setPhoto(i)} key={src+i}><img src={src} alt=""/></button>)}</div></div><div><Link href="/shop" className="eyebrow muted">Shop / {product.collection}</Link><h1>{product.name}</h1><p className="muted">{product.description}</p><div className="pricebig">{money(product.price)}</div>{claimed&&settings.offerEnabled&&<p className="success" style={{marginTop:12}}>First-purchase offer claimed · {settings.offerPercent}% off eligible purchases</p>}<div className="purchase"><h3>The details</h3><p>{product.specs}</p><h3>Payment</h3><p>{product.paymentPlan}</p><p className="muted" style={{fontSize:14}}>Request your watch below. We confirm availability and share bank details on WhatsApp. Your order is marked paid after we verify the transfer.</p>{product.demo?<div className="notice">Collection preview only. This is reference imagery, not a product offered for sale. Purchases open once the actual catalogue is added.</div>:order?<div className="notice"><h3>Request received.</h3><p>Reference: {order.id}<br/>Total: {money(order.total)}</p><a className="pill" href={order.whatsappUrl} target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a><p style={{marginTop:15}}>Press Send in WhatsApp to share your request.</p></div>:<><form className="form" onSubmit={requestPurchase}>{!claimed&&settings.offerEnabled&&<div className="notice"><strong>{settings.offerPercent}% off your first purchase</strong><p>{settings.offerText}</p><button className="pill outline" type="button" disabled={busy} onClick={claim}>{busy?"Claiming…":"Claim this offer"}</button></div>}<label>Your name<input required name="name" maxLength={100} autoComplete="name"/></label><label>WhatsApp number<input required name="phone" type="tel" autoComplete="tel" maxLength={25}/></label><label>Returning-customer offer code <span className="muted">Optional</span><input name="offerCode" maxLength={40} placeholder="Your personal code" autoComplete="off"/></label><label>Anything you would like to ask? <span className="muted">Optional</span><textarea name="note" maxLength={1000}/></label><button className="pill" disabled={busy||!settings.whatsapp}>{busy?"Saving your request…":"Request to purchase"}</button>{!settings.whatsapp&&<small>Purchase requests are not open yet.</small>}</form></>}</div></div></section>:<div className="reading"><h2>Watch not found</h2><Link href="/shop">Return to the collection</Link></div>)}
{error&&<p className="notice error" role="alert" style={{margin:"20px 7%"}}>{error}</p>}</main>
<SiteFooter/>
<Dialog open={!!quick} onOpenChange={v=>{if(!v)setQuick(null)}}><DialogContent style={{maxWidth:850,width:"calc(100% - 32px)",padding:35}}>{quick&&<div className="quickgrid"><img src={quick.images[0]} alt={quick.name}/><div><span className="eyebrow muted">{quick.collection}</span><DialogTitle style={{fontSize:34,letterSpacing:"-.04em",margin:"15px 0"}}>{quick.name}</DialogTitle><DialogDescription style={{lineHeight:1.7,marginBottom:20}}>{quick.description}</DialogDescription><p className="pricebig">{money(quick.price)}</p><a className="pill" href={"/shop/"+(quick.slug||quick.id)}>Explore this watch <ArrowUpRight size={18}/></a></div></div>}</DialogContent></Dialog>
<Dialog open={offer} onOpenChange={open=>{if(open)setOffer(true);else dismissOffer()}}><DialogContent><div className="offer"><span className="eyebrow">A first welcome</span><strong>{settings.offerPercent}%</strong><DialogTitle style={{fontSize:30,margin:"5px 0 15px"}}>{settings.offerTitle}</DialogTitle><DialogDescription>{settings.offerText} Applied to your first eligible purchase request.</DialogDescription><button className="pill" style={{margin:"25px 0 15px",width:"100%"}} disabled={busy} onClick={claim}>{busy?"Claiming…":"Claim my offer"}</button><button className="textlink" onClick={dismissOffer}>Continue browsing</button><p className="muted" style={{fontSize:12,marginTop:20}}>One first-purchase offer per customer. No payment required to claim.</p></div></DialogContent></Dialog>
</>}
