export type Product={id:string;name:string;collection:string;price:number;description:string;specs:string;images:string[];featured:boolean;active:boolean;demo?:boolean;paymentPlan:string};
export const samples:Product[]=[
{id:"preview-steel",name:"The steel edit",collection:"Everyday",price:95000,description:"A preview of the Stacdial collection. Actual product photographs, specifications and availability will be added before sales open.",specs:"Product specifications to be confirmed.",images:["/images/watch-1.jpg"],featured:true,active:true,demo:true,paymentPlan:"Bank transfer. Payment arrangements are confirmed with Stacdial before purchase."},
{id:"preview-gold",name:"The silver dial edit",collection:"Dress",price:145000,description:"A preview of the Stacdial collection. Actual product photographs, specifications and availability will be added before sales open.",specs:"Product specifications to be confirmed.",images:["/images/watch-2.jpg"],featured:true,active:true,demo:true,paymentPlan:"Bank transfer. Payment arrangements are confirmed with Stacdial before purchase."},
{id:"preview-dark",name:"The dark dial edit",collection:"Sport",price:185000,description:"A preview of the Stacdial collection. Actual product photographs, specifications and availability will be added before sales open.",specs:"Product specifications to be confirmed.",images:["/images/watch-3.jpg"],featured:true,active:true,demo:true,paymentPlan:"Bank transfer. Payment arrangements are confirmed with Stacdial before purchase."}
];
export type Crop={x:number;y:number;zoom:number;fit:"cover"|"contain"};
export const defaultCrop:Crop={x:50,y:50,zoom:1,fit:"cover"};
export const defaults={shopCover:"",aboutCover:"",shopCrop:{...defaultCrop},aboutCrop:{...defaultCrop},shopMobileCrop:{...defaultCrop},aboutMobileCrop:{...defaultCrop},editorialImage:"/images/hero.jpg",editorialCrop:{...defaultCrop},editorialMobileCrop:{...defaultCrop},editorialTitle:"It’s all in the details.",editorialText:"The way a dial catches the light. The balance of a case. The feel of a bracelet. Take a closer look at the details that make a watch yours.",consultationEnabled:true,desktopVideo:"/videos/watchpc.mp4",mobileVideo:"/videos/mobile.mp4",poster:"/images/hero.jpg",whatsapp:"94760436776",offerPercent:5,offerEnabled:true,offerTitle:"Your first Stacdial.",offerText:"A little something for your first watch.",about:"Stacdial is a Sri Lanka-based watch store for people who appreciate the look and feel of a considered timepiece. We offer superclone watches, with prices typically ranging from LKR 50,000 to LKR 200,000. Prices vary by model and availability.",sheetsId:"1ljq3p8armJ5Ua042uKqOSzf90CjGQo97WNISRACRW-8"};
export const money=(n:number)=>"LKR "+new Intl.NumberFormat("en-LK",{maximumFractionDigits:2}).format(n);
