import {runtime,db,readSettings} from "./server";
const encode=(s:Uint8Array)=>btoa(String.fromCharCode(...s)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");
export async function syncOrders(){
const config=runtime().GOOGLE_SERVICE_ACCOUNT_JSON;if(!config)return {configured:false};
const settings=await readSettings();if(!/^[a-zA-Z0-9_-]{15,150}$/.test(settings.sheetsId))return {configured:false};
const account=JSON.parse(config),now=Math.floor(Date.now()/1000),te=new TextEncoder();const header=encode(te.encode(JSON.stringify({alg:"RS256",typ:"JWT"})));const payload=encode(te.encode(JSON.stringify({iss:account.client_email,scope:"https://www.googleapis.com/auth/spreadsheets",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})));const unsigned=header+"."+payload;
const pem=account.private_key.replace(/-----[^-]+-----|\s/g,"");const key=await crypto.subtle.importKey("pkcs8",Uint8Array.from(atob(pem),c=>c.charCodeAt(0)),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,te.encode(unsigned));
const tokenResponse=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:unsigned+"."+encode(new Uint8Array(sig))}),signal:AbortSignal.timeout(8000)});if(!tokenResponse.ok)throw Error("Google authentication failed");const token:any=await tokenResponse.json();
const rows:any=await db().prepare("SELECT * FROM orders ORDER BY created ASC LIMIT 5000").all();const values=[["Request","Date","Customer","WhatsApp","Watch","Subtotal LKR","Discount LKR","Total LKR","Status"],...rows.results.map((o:any)=>[o.id,new Date(o.created).toISOString(),o.name,o.phone,o.product_name,o.subtotal/100,o.discount/100,o.total/100,o.status])];
const r=await fetch("https://sheets.googleapis.com/v4/spreadsheets/"+settings.sheetsId+"/values/Orders!A1:I5001?valueInputOption=RAW",{method:"PUT",headers:{Authorization:"Bearer "+token.access_token,"Content-Type":"application/json"},body:JSON.stringify({range:"Orders!A1:I5001",majorDimension:"ROWS",values}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error("Sheet update failed. Check access and the Orders tab.");await db().prepare("UPDATE orders SET synced=1 WHERE updated<=?").bind(Date.now()).run();return {configured:true,synced:rows.results.length}}
