import {admin,json,readSettings,readProducts,db,body,originCheck,log,runtime} from "@/lib/server";
import {syncOrders} from "@/lib/sheets";
import {z} from "zod";
const asset=z.string().regex(/^\/(images\/[a-zA-Z0-9_.-]+|videos\/[a-zA-Z0-9_.-]+|api\/media\/[a-zA-Z0-9_.-]+)$/);
const productSchema=z.object({id:z.string().regex(/^[a-zA-Z0-9-]{1,70}$/),name:z.string().min(2).max(100),collection:z.string().min(1).max(50),price:z.number().min(1).max(100000000),description:z.string().max(3000),specs:z.string().max(3000),images:z.array(asset).min(1).max(12),featured:z.boolean(),active:z.boolean(),paymentPlan:z.string().max(2000)});
const cropSchema=z.object({x:z.number().min(0).max(100),y:z.number().min(0).max(100),zoom:z.number().min(1).max(3),fit:z.enum(["cover","contain"])});
const settingsSchema=z.object({shopCover:z.union([asset,z.literal("")]),aboutCover:z.union([asset,z.literal("")]),shopCrop:cropSchema,aboutCrop:cropSchema,shopMobileCrop:cropSchema,aboutMobileCrop:cropSchema,editorialImage:asset,editorialCrop:cropSchema,editorialMobileCrop:cropSchema,editorialTitle:z.string().min(1).max(100),editorialText:z.string().max(1000),consultationEnabled:z.boolean(),desktopVideo:z.union([asset,z.literal("")]),mobileVideo:z.union([asset,z.literal("")]),poster:asset,whatsapp:z.string().regex(/^$|^[1-9][0-9]{8,14}$/),offerPercent:z.number().min(0).max(50),offerEnabled:z.boolean(),offerTitle:z.string().min(1).max(100),offerText:z.string().max(300),about:z.string().max(5000),sheetsId:z.string().regex(/^$|^[a-zA-Z0-9_-]{15,150}$/)});
export async function GET(){const u=await admin();if(!u)return json({error:"Administrator access required"},403);try{const rows=await db().prepare("SELECT * FROM orders ORDER BY created DESC LIMIT 5000").all();return json({settings:await readSettings(),products:await readProducts(false),orders:rows.results,loyaltyOffers:(await db().prepare("SELECT * FROM loyalty_offers ORDER BY created DESC LIMIT 1000").all()).results,sheetsConfigured:!!runtime().GOOGLE_SERVICE_ACCOUNT_JSON})}catch(e){console.error(e);return json({error:"Dashboard unavailable"},503)}}
export async function POST(req:Request){const u=await admin();if(!u)return json({error:"Administrator access required"},403);try{originCheck(req);const b=await body(req);if(b.action==="settings"){const s=settingsSchema.parse(b.data);await db().prepare("INSERT INTO settings (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data").bind("store",JSON.stringify(s)).run();await log(u.userId,"settings updated");return json({ok:true})}
if(b.action==="product"){const p=productSchema.parse(b.data);await db().prepare("INSERT INTO products (id,data,active) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,active=excluded.active").bind(p.id,JSON.stringify(p),p.active?1:0).run();await log(u.userId,"product saved:"+p.id);return json({ok:true})}
if(b.action==="paid"){const id=z.string().max(30).parse(b.id);const result=await db().prepare("UPDATE orders SET status='paid',updated=?,synced=0 WHERE id=? AND status='requested'").bind(Date.now(),id).run();if(!result.meta.changes)return json({error:"Request not found or already paid"},400);await log(u.userId,"payment verified:"+id);let sync;try{sync=await syncOrders()}catch{sync={error:"Payment saved; sheet sync pending"}}return json({ok:true,sync})}
if(b.action==="loyalty"){const offer=z.object({phone:z.string().regex(/^[1-9][0-9]{8,14}$/),percent:z.number().int().min(1).max(50),minimum:z.number().min(0).max(100000000),expires:z.number().int().refine(v=>v>Date.now()&&v<Date.now()+366*86400000)}).parse(b.data);const paid=await db().prepare("SELECT id FROM orders WHERE phone=? AND status='paid' LIMIT 1").bind(offer.phone).first();if(!paid)return json({error:"Choose a customer with a confirmed purchase"},400);const code="STAC-"+crypto.randomUUID().replace(/-/g,"").slice(0,16).toUpperCase();await db().prepare("INSERT INTO loyalty_offers (code,phone,percent,minimum,expires,used_order,active,created) VALUES (?,?,?,?,?,NULL,1,?)").bind(code,offer.phone,offer.percent,Math.round(offer.minimum*100),offer.expires,Date.now()).run();await log(u.userId,"personal offer created:"+code);return json({ok:true,code})}
if(b.action==="revokeLoyalty"){const code=z.string().max(40).parse(b.id);await db().prepare("UPDATE loyalty_offers SET active=0 WHERE code=? AND used_order IS NULL").bind(code).run();await log(u.userId,"personal offer revoked:"+code);return json({ok:true})}
if(b.action==="sync")return json(await syncOrders());return json({error:"Unknown action"},400)}catch(e:any){console.error(e);return json({error:e.name==="ZodError"?"Please check all fields and media files.":e.message||"Unable to save"},400)}}
