import {syncOrders} from "@/lib/sheets";
import {adminActionSchema} from "@/lib/schemas";
import {firestore} from "@/lib/firebase-admin";
import {listCollection,listFirestoreOrders,readFirestoreOrder,updateFirestoreOrder,writeCollectionDoc,writeFirestoreProduct,writeFirestoreSettings} from "@/lib/firestore-store";
import {AppError,admin,body,errorResponse,json,log,originCheck,readProducts,readSettings,runtime} from "@/lib/server";

export async function GET(){if(!(await admin()))return json({error:"Administrator access required"},403);try{return json({settings:await readSettings(),products:await readProducts(false),orders:await listFirestoreOrders(5000),loyaltyOffers:await listCollection("loyaltyOffers",1000,"created"),sheetsConfigured:Boolean(runtime().GOOGLE_SERVICE_ACCOUNT_JSON),media:await listCollection("media",1000,"updated")})}catch(error){return errorResponse(error,"Dashboard unavailable")}}

export async function POST(req:Request){const user=await admin();if(!user)return json({error:"Administrator access required"},403);try{originCheck(req);const input=adminActionSchema.parse(await body(req,35_000));if(input.action==="settings"){await writeFirestoreSettings(input.data);await log(user.userId,"settings updated");return json({ok:true})}if(input.action==="product"){await writeFirestoreProduct(input.data);await log(user.userId,`product saved:${input.data.id}`);return json({ok:true})}if(input.action==="paid"){const order=await readFirestoreOrder(input.id);if(!order||order.status!=="requested")throw new AppError("Request not found or already paid",409,"CONFLICT");await updateFirestoreOrder(input.id,{status:"paid",synced:0});await log(user.userId,`payment verified:${input.id}`);void syncOrders().catch(error=>console.error("Sheet sync pending",error));return json({ok:true,syncQueued:true})}if(input.action==="loyalty"){const offer=input.data;if(offer.expires<=Date.now()||offer.expires>=Date.now()+366*86_400_000)throw new AppError("Choose an expiry within the next year",400,"BAD_REQUEST");const paid=await firestore().collection("orders").where("phone","==",offer.phone).where("status","==","paid").limit(1).get();if(paid.empty)throw new AppError("Choose a customer with a confirmed purchase",400,"BAD_REQUEST");const code=`STAC-${crypto.randomUUID().replace(/-/g,"").slice(0,16).toUpperCase()}`;await writeCollectionDoc("loyaltyOffers",code,{code,phone:offer.phone,percent:offer.percent,minimum:Math.round(offer.minimum*100),expires:offer.expires,used_order:null,active:true,created:Date.now()});await log(user.userId,`personal offer created:${code}`);return json({ok:true,code})}if(input.action==="revokeLoyalty"){const ref=firestore().collection("loyaltyOffers").doc(input.id);const snap=await ref.get();if(snap.exists&&!snap.data()?.used_order)await ref.update({active:false});await log(user.userId,`personal offer revoked:${input.id}`);return json({ok:true})}return json(await syncOrders())}catch(error){return errorResponse(error,"Unable to save dashboard changes")}}
