import {getChatGPTUser} from "@/app/chatgpt-auth";
import {firestore} from "@/lib/firebase-admin";
import {normalizePhone,orderSchema} from "@/lib/schemas";
import {AppError,body,claimToken,errorResponse,json,limit,originCheck,readSettings} from "@/lib/server";
import {createFirestoreOrder,findOrderByRequestKey,listUserOrders,readCollectionDoc,readFirestoreProduct,type OrderRecord} from "@/lib/firestore-store";
import {syncOrders} from "@/lib/sheets";

type Offer={phone:string;percent:number;minimum:number;expires:number;used_order?:string|null;active:boolean};
function response(order:OrderRecord,whatsapp:string){const message=`Hello Stacdial, I would like to purchase ${order.product_name}. Request: ${order.id}. Total: LKR ${(order.total/100).toLocaleString("en-LK")}. Name: ${order.name}. Please confirm availability and payment details.`;return json({id:order.id,total:order.total/100,whatsappUrl:`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`})}

export async function POST(req:Request){try{originCheck(req);await limit(req,"orders",10);const input=orderSchema.parse(await body(req,5_000));const phone=normalizePhone(input.phone);if(!/^[1-9][0-9]{8,14}$/.test(phone))throw new AppError("Please check your WhatsApp number",400,"BAD_REQUEST");const settings=await readSettings();if(!/^[1-9][0-9]{8,14}$/.test(settings.whatsapp))throw new AppError("Purchase requests are not open yet",503,"UNAVAILABLE");const existing=await findOrderByRequestKey(input.requestKey);if(existing){if(existing.phone!==phone||existing.name!==input.name)throw new AppError("Invalid request",400,"BAD_REQUEST");return response(existing,settings.whatsapp)}const product=await readFirestoreProduct(input.productId);if(!product||!product.active)throw new AppError("This watch is unavailable",404,"NOT_FOUND");const subtotal=Math.round(product.price*100);if(product.demo||product.inStock===false||subtotal<=0)throw new AppError("This watch is not available for purchase",400,"BAD_REQUEST");const id=`SD-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const user=await getChatGPTUser();const now=Date.now();let discount=0;const offerCode=input.offerCode.toUpperCase();if(offerCode){if(!/^STAC-[A-Z0-9]{16}$/.test(offerCode))throw new AppError("Please check your personal offer code",400,"BAD_REQUEST");const offer=await readCollectionDoc<Offer>("loyaltyOffers",offerCode);if(!offer||offer.phone!==phone||!offer.active||offer.used_order||offer.expires<=now||offer.minimum>subtotal)throw new AppError("This offer is unavailable, expired, or already used",400,"BAD_REQUEST");discount=Math.round(subtotal*offer.percent/100)}else{const token=claimToken(req);const claim=token?await readCollectionDoc<{used:boolean}>("claims",token):null;const previous=await firestore().collection("orders").where("phone","==",phone).limit(1).get();if(claim&&!claim.used&&previous.empty&&settings.offerEnabled)discount=Math.round(subtotal*settings.offerPercent/100)}const order:OrderRecord={id,request_key:input.requestKey,user_id:user?.userId??null,name:input.name,email:user?.email||"",phone,contact_preference:"either",alternative_phone:"",delivery_address:"",city:"",note:input.note,internal_notes:"",product_id:product.id,product_name:product.name,subtotal,discount,total:subtotal-discount,status:"requested",created:now,updated:now,synced:0};await createFirestoreOrder(order);if(offerCode)await firestore().collection("loyaltyOffers").doc(offerCode).update({used_order:id});else{const token=claimToken(req);if(token&&discount>0)await firestore().collection("claims").doc(token).update({used:true})}void syncOrders().catch(error=>console.error("Sheet sync pending",error));return response(order,settings.whatsapp)}catch(error){return errorResponse(error,"Unable to save your request")}}
export async function GET(){try{const user=await getChatGPTUser();if(!user)throw new AppError("Sign in required",401,"UNAUTHORIZED");return json(await listUserOrders(user.userId))}catch(error){return errorResponse(error,"Requests unavailable")}}
